//! This is the instrument code that should ultimately be generated by a macro.

use std::io::{Read, Write};

use instrumentrs::transport::{Transport, Writable};

use crate::{
    InstrumentError,
    types::{
        AlarmFlags, DischargePressure, DischargeTemperature, ElectricConductivity, FlowRate,
        OperationStatus, SerialRemoteInstruction, SetTemperature, SilentInterval, SlaveAddress,
        StatusFlag,
    },
};

pub trait InstrumentParameter<W: Writable>: Sized {
    fn to_writable(&self) -> W;
    fn try_from_writable(val: W) -> Result<Self, InstrumentError>;
}

pub struct SmcHrr<I: Read + Write> {
    pub(crate) interface: I,
    pub slave_address: SlaveAddress,
    pub(crate) silent_interval: SilentInterval,
}

impl<I: Read + Write> SmcHrr<I> {
    /// Create a new SmcHrr chiller instance with a default base address of 1.
    ///
    /// Arguments:
    /// - interface: The communication interface.
    /// - slave_address: Provide slave address. Defaults to 1 if `None` given.
    pub fn new(interface: I) -> Self {
        Self {
            interface,
            slave_address: Default::default(),
            silent_interval: Default::default(),
        }
    }

    /// Create a new SmcHrr with a specific base address.
    ///
    /// Arguments:
    /// - interface: The communication interface.
    /// - slave_address: Provide slave address. Defaults to 1 if `None` given.
    pub fn new_with_slave_address(interface: I, slave_address: SlaveAddress) -> Self {
        Self {
            interface,
            slave_address,
            silent_interval: Default::default(),
        }
    }

    pub fn get_discharge_pressure(&mut self) -> Result<DischargePressure, InstrumentError> {
        let res = self.query(&[0x00, 0x02, 0x00, 0x01], None, None)?;
        DischargePressure::try_from_writable(res)
    }

    pub fn get_discharge_temperature(&mut self) -> Result<DischargeTemperature, InstrumentError> {
        let res = self.query(&[0x00, 0x00, 0x00, 0x01], None, None)?;
        DischargeTemperature::try_from_writable(res)
    }

    pub fn get_electric_conductivity(&mut self) -> Result<ElectricConductivity, InstrumentError> {
        let res = self.query(&[0x00, 0x03, 0x00, 0x01], None, None)?;
        ElectricConductivity::try_from_writable(res)
    }

    pub fn get_flow_rate(&mut self) -> Result<FlowRate, InstrumentError> {
        let res = self.query(&[0x00, 0x01, 0x00, 0x01], None, None)?;
        FlowRate::try_from_writable(res)
    }

    pub fn get_operation_status(&mut self) -> Result<OperationStatus, InstrumentError> {
        let res = self.query(&[0x00, 0x0C, 0x00, 0x01], None, None)?;
        OperationStatus::try_from_writable(res)
    }

    pub fn set_operation_status(&mut self, value: OperationStatus) -> Result<(), InstrumentError> {
        self.sendcmd(&[0x00, 0x0C], None, Some(&[&value.to_writable()]))
    }

    pub fn get_set_temperature(&mut self) -> Result<SetTemperature, InstrumentError> {
        let res = self.query(&[0x00, 0x0B, 0x00, 0x01], None, None)?;
        SetTemperature::try_from_writable(res)
    }

    pub fn get_alarm_flags(&mut self) -> Result<AlarmFlags, InstrumentError> {
        let res = self.query(&[0x00, 0x05, 0x00, 0x02], None, None)?;
        AlarmFlags::try_from_writable(res)
    }

    pub fn get_status(&mut self) -> Result<StatusFlag, InstrumentError> {
        let res = self.query(&[0x00, 0x04, 0x00, 0x01], None, None)?;
        StatusFlag::try_from_writable(res)
    }

    /// Set the set temperature of the chiller.
    pub fn set_set_temperature(&mut self, value: SetTemperature) -> Result<(), InstrumentError> {
        self.sendcmd(&[0x00, 0x0B], None, Some(&[value.to_writable().as_slice()]))
    }

    /// Get the serial remote instructions.
    pub fn get_serial_remote_instructions(
        &mut self,
    ) -> Result<SerialRemoteInstruction, InstrumentError> {
        let ret = self.query(&[0x00, 0x0C, 0x00, 0x01], None, None)?;
        SerialRemoteInstruction::try_from_writable(ret)
    }
}

// implementations that cannot be handled automatically in the near future.
impl<I: Read + Write> SmcHrr<I> {
    /// Set the serial remote instruction to a specific value.
    ///
    /// This command will first check the status of the chiller by reading the status flags. It will
    /// then set the serial remote instruction to the wanted value while keeping the operating
    /// condition (running or stopped) as it currently is.
    pub fn set_serial_remote_instructions(
        &mut self,
        value: SerialRemoteInstruction,
    ) -> Result<(), InstrumentError> {
        let mut args = value.to_writable();

        let st = self.get_status()?;
        if st.is_running() {
            args[1] += 0x01;
        }

        // write 1 to bits 4 and 5
        self.sendcmd(&[0x00, 0x0C], None, Some(&[&args]))
    }
}
