//! This is the instrument code that should ultimately be generated by a macro.
//!
//! Not at the bottom of this file we impl some special functions that the macro will not cover (for
//! now?).

use std::io::{Read, Write};

use instrumentrs2::transport::{Transport, Writable};
use measurements::{Fraction, Temperature};

use crate::{
    InstrumentRsError,
    channel::{Channel, Input, Output},
    types::{HeaterSetup, OutputModeSetup, heater_setup::HeaterRange},
};

pub trait Parameter<W: Writable>: Sized {
    fn to_writable(&self) -> W;
    fn try_from_writable(val: W) -> Result<Self, InstrumentRsError>;
}

pub struct Lakeshore336<I: Read + Write> {
    pub(crate) interface: I,
    pub terminator: String,
}

impl<I: Read + Write> Lakeshore336<I> {
    pub fn new(interface: I) -> Self {
        Self {
            interface,
            terminator: String::from("\n"),
        }
    }

    pub fn channel(&mut self, idx: Input) -> Lakeshore336Channel<'_, I> {
        Lakeshore336Channel::new(idx, self)
    }

    pub fn output(&mut self, idx: Output) -> Lakeshore336Output<'_, I> {
        Lakeshore336Output::new(idx, self)
    }

    /// Obtain the identification (name) of the instrument.
    ///
    /// Returns:
    ///
    /// Result with a string holding the following information:
    /// <manufacturer>,<model>,<instrument serial>/<option serial>,<firmware version>
    pub fn get_name(&mut self) -> Result<String, InstrumentRsError> {
        let res = self.query("*IDN?", None, None)?;
        String::try_from_writable(res)
    }
}

pub struct Lakeshore336Channel<'a, I: Read + Write> {
    device: &'a mut Lakeshore336<I>,
    idx: Input,
}

impl<'d, I: Read + Write> Lakeshore336Channel<'d, I> {
    /// Returns a new channel. This can only be done through the device.
    fn new(idx: Input, device: &'d mut Lakeshore336<I>) -> Self {
        Self { device, idx }
    }

    /// Get the name of a channel.
    pub fn get_channel_name(&mut self) -> Result<String, InstrumentRsError> {
        let res = self
            .device
            .query("INNAME?", Some(Channel::In(self.idx)), None)?;
        String::try_from_writable(res)
    }

    /// Set the name of a channel.
    pub fn set_channel_name(&mut self, channel_name: &str) -> Result<(), InstrumentRsError> {
        let wrapped = format!("\"{}\"", channel_name);
        self.device
            .sendcmd("INNAME", Some(Channel::In(self.idx)), Some(&[&wrapped]))
    }

    pub fn get_temperature(&mut self) -> Result<Temperature, InstrumentRsError> {
        let res = self
            .device
            .query("KRDG?", Some(Channel::In(self.idx)), None)?;
        Temperature::try_from_writable(res)
    }
}

pub struct Lakeshore336Output<'a, I: Read + Write> {
    device: &'a mut Lakeshore336<I>,
    idx: Output,
}

impl<'d, I: Read + Write> Lakeshore336Output<'d, I> {
    /// Returns a new channel. This can only be done through the device.
    fn new(idx: Output, device: &'d mut Lakeshore336<I>) -> Self {
        Self { device, idx }
    }

    /// Get the heater setup.
    pub fn get_heater_setup(&mut self) -> Result<HeaterSetup, InstrumentRsError> {
        let res = self
            .device
            .query("HTRSET?", Some(Channel::Out(self.idx)), None)?;
        HeaterSetup::try_from_writable(res)
    }

    /// Set the heater setup.
    pub fn set_heater_setup(&mut self, heater_setup: HeaterSetup) -> Result<(), InstrumentRsError> {
        self.device.sendcmd(
            "HTRSET",
            Some(Channel::Out(self.idx)),
            Some(&[&heater_setup.to_writable()]),
        )
    }

    /// Get the output mode.
    pub fn get_output_mode(&mut self) -> Result<OutputModeSetup, InstrumentRsError> {
        let res = self
            .device
            .query("OUTMODE?", Some(Channel::Out(self.idx)), None)?;
        OutputModeSetup::try_from_writable(res)
    }

    /// Set the output mode.
    pub fn set_output_mode(
        &mut self,
        output_mode_setup: OutputModeSetup,
    ) -> Result<(), InstrumentRsError> {
        self.device.sendcmd(
            "OUTMODE",
            Some(Channel::Out(self.idx)),
            Some(&[&output_mode_setup.to_writable()]),
        )
    }

    /// Get the heater range.
    pub fn get_range(&mut self) -> Result<HeaterRange, InstrumentRsError> {
        let res = self
            .device
            .query("RANGE?", Some(Channel::Out(self.idx)), None)?;
        HeaterRange::try_from_writable(res)
    }

    /// Set the heater range.
    ///
    /// This command can be used to turn the heater on or off.
    ///
    /// Note: For outputs Out1 and Out2, all ranges are valid. For Out3 and Out4, the output can
    /// only be on or off.
    pub fn set_range(&mut self, range: HeaterRange) -> Result<(), InstrumentRsError> {
        self.device.sendcmd(
            "RANGE",
            Some(Channel::Out(self.idx)),
            Some(&[&range.to_writable()]),
        )
    }

    /// Get the setpoint of this output.
    ///
    /// Note: This assumes that the sensor is set up in Kelvin mode. If this is not the case, the
    /// setpoint that is returned will be wrong.
    pub fn get_setpoint(&mut self) -> Result<Temperature, InstrumentRsError> {
        let res = self
            .device
            .query("SETP?", Some(Channel::Out(self.idx)), None)?;
        Temperature::try_from_writable(res)
    }

    /// Set the setpoint of this output.
    /// Note: This assumes that the sensor is set up in Kelvin mode. If this is not the case, the
    /// setpoint will be set up wrong.
    pub fn set_setpoint(&mut self, setpoint: Temperature) -> Result<(), InstrumentRsError> {
        self.device.sendcmd(
            "SETP",
            Some(Channel::Out(self.idx)),
            Some(&[&setpoint.to_writable()]),
        )
    }
}

// Some special functions that the macro will not cover for now.

impl<'d, I: Read + Write> Lakeshore336Output<'d, I> {
    /// Get the heater output.
    ///
    /// Heater output as a fraction of the total output power/current.
    /// For output channels 1 and 2, this queries the heater output in % using the "HTR?" command.
    /// For output channels 3 and 4, the output percentage of the unpowered analog output is queried
    /// using the "AOUT?" command.
    pub fn get_heater_output(&mut self) -> Result<Fraction, InstrumentRsError> {
        let res = match self.idx {
            Output::Out1 | Output::Out2 => {
                self.device
                    .query("HTR?", Some(Channel::Out(self.idx)), None)?
            }
            Output::Out3 | Output::Out4 => {
                self.device
                    .query("AOUT?", Some(Channel::Out(self.idx)), None)?
            }
        };
        Fraction::try_from_writable(res)
    }
}
